name: Detekt Check

on:
  pull_request:
    branches:
      - main

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'  # Specify the desired Java version here

      - name: Run Detekt
        run: ./gradlew detekt
